"""Make robosuite 1.4.1 importable and renderable on Windows.

robosuite officially supports Linux and macOS only. Two things break on Windows,
both before any environment is constructed, and both are patches to the installed
package rather than anything expressible in ``requirements.txt``:

1. ``robosuite/utils/binding_utils.py`` opens ``mujoco.dll`` from its own
   directory with ``ctypes.WinDLL``. The MuJoCo wheel ships that DLL inside the
   ``mujoco`` package, not inside robosuite, so the import fails with
   ``FileNotFoundError`` until it is copied across.

2. With ``macros.MUJOCO_GPU_RENDERING = True`` (the default), robosuite forces
   ``MUJOCO_GL=egl``. Its own validator then rejects ``egl`` on Windows, where the
   only accepted values are ``wgl`` and ``glfw``. So the default configuration
   always raises ``RuntimeError`` on this platform. Writing a private macro that
   disables the flag leaves ``MUJOCO_GL`` alone. This does not move rendering onto
   the CPU -- the GLFW/WGL context still runs on the GPU.

3. ``robomimic`` depends on ``egl_probe``, which compiles against EGL headers with
   CMake and therefore cannot be built on Windows. ``robomimic.envs.env_robosuite``
   imports it unconditionally whenever offscreen rendering is requested, which is
   exactly the path dataset replay takes in Phase 3. A stub reporting zero EGL
   devices is the semantically correct answer here -- Windows has none -- and
   robosuite then falls back to its default device selection.

Separately, and not a bug in anyone's code: on this Optimus laptop the WGL context
is handed to whichever GPU the driver thinks the process wants. A process that has
not touched CUDA gets the Intel integrated GPU, which renders the two-camera Lift
step in ~47 ms. Creating a CUDA context first gets the RTX 4050 and ~7 ms, measured
back to back and reproducibly. :func:`configure_rendering` therefore initialises
CUDA before robosuite builds its context.

Call :func:`configure_rendering` before importing robosuite. It is idempotent and
a no-op on Linux and macOS.
"""

from __future__ import annotations

import logging
import os
import shutil
import sys
import types
from pathlib import Path

logger = logging.getLogger(__name__)

# Only value robosuite accepts on Windows that maps to a GPU context. "glfw" is
# also accepted and resolves to the same backend; "wgl" is the explicit spelling.
WINDOWS_MUJOCO_GL = "wgl"

_MACROS_HEADER = '''\
"""Generated by src/envs/robosuite_compat.py. Do not edit by hand."""

# robosuite renders in the OpenGL convention, whose origin is bottom-left, so
# rendered frames come back flipped vertically. Verified by eye in Phase 2: with the
# default setting `agentview` puts the robot and the floor at the bottom of the
# frame and the table above them. "opencv" gives the orientation every downstream
# consumer assumes -- SmolVLA's vision encoder, saved debug frames, and the images
# robomimic regenerates in Phase 3.
#
# Setting it here rather than flipping inside the observation adapter keeps one
# source of truth. Phase 3 regenerates images through robomimic, which never sees
# our adapter, and an adapter-side flip would silently desynchronise the two.
IMAGE_CONVENTION = "opencv"
'''

_MACROS_WINDOWS = '''
# robosuite forces MUJOCO_GL=egl when MUJOCO_GPU_RENDERING is True, but its own
# validator rejects egl on Windows. Disabling the flag leaves MUJOCO_GL alone so the
# GLFW/WGL context is used, which still renders on the GPU.
MUJOCO_GPU_RENDERING = False
'''


def _package_dir(name: str) -> Path:
    """Locate an installed package without importing it."""
    import importlib.util

    spec = importlib.util.find_spec(name)
    if spec is None or not spec.submodule_search_locations:
        raise ModuleNotFoundError(f"{name} is not installed")
    return Path(list(spec.submodule_search_locations)[0])


def _copy_mujoco_dll() -> bool:
    """Copy mujoco.dll into robosuite/utils. Returns True if a copy was made."""
    src = _package_dir("mujoco") / "mujoco.dll"
    dst = _package_dir("robosuite") / "utils" / "mujoco.dll"

    if not src.is_file():
        raise FileNotFoundError(f"mujoco.dll not found at {src}")

    # Re-copy when the MuJoCo version changes, otherwise robosuite keeps loading a
    # stale DLL that no longer matches the Python bindings.
    if dst.is_file() and dst.stat().st_size == src.stat().st_size:
        return False

    shutil.copy2(src, dst)
    logger.info("copied %s -> %s", src, dst)
    return True


def _write_private_macros() -> bool:
    """Write robosuite/macros_private.py. Returns True if written.

    The image convention applies on every platform; the GPU rendering override is
    Windows-only, because on Linux that flag is what selects EGL.
    """
    content = _MACROS_HEADER
    if sys.platform == "win32":
        content += _MACROS_WINDOWS

    dst = _package_dir("robosuite") / "macros_private.py"
    if dst.is_file() and dst.read_text(encoding="utf-8") == content:
        return False
    dst.write_text(content, encoding="utf-8")
    logger.info("wrote %s", dst)
    return True


def _stub_egl_probe() -> bool:
    """Register a no-op ``egl_probe`` module. Returns True if a stub was installed.

    robomimic calls ``egl_probe.get_available_devices()`` purely to pick a GPU for
    an EGL context. Windows has no EGL devices, so an empty list is the honest
    answer and leaves robosuite on its default device.
    """
    import importlib.util

    if "egl_probe" in sys.modules:
        return False
    try:
        if importlib.util.find_spec("egl_probe") is not None:
            return False
    except (ImportError, ValueError):
        pass

    module = types.ModuleType("egl_probe")
    module.__doc__ = "Stub installed by src/envs/robosuite_compat.py (Windows)."
    module.get_available_devices = lambda: []  # type: ignore[attr-defined]
    sys.modules["egl_probe"] = module
    logger.info("installed egl_probe stub")
    return True


def prefer_discrete_gpu() -> bool:
    """Claim the discrete GPU for OpenGL by creating a CUDA context first.

    On an Optimus laptop the WGL context follows whatever the driver believes the
    process needs. Without this, robosuite renders on the Intel integrated GPU.
    Measured on the Lift task with two 128px cameras: ~47 ms per step on the
    integrated GPU against ~7 ms on the RTX 4050, with p95 following the same
    ratio. The call is cheap and must happen before the render context exists.

    Returns:
        True if a CUDA context was created.
    """
    try:
        import torch

        if not torch.cuda.is_available():
            logger.warning("CUDA unavailable; rendering may fall back to the iGPU")
            return False
        torch.zeros(1, device="cuda")
        return True
    except Exception as exc:  # noqa: BLE001 - never block rendering over this
        logger.warning("could not claim the discrete GPU: %s", exc)
        return False


def configure_rendering(mujoco_gl: str | None = None, init_cuda: bool = True) -> str:
    """Prepare the process for offscreen robosuite rendering.

    Must be called before ``import robosuite``.

    Args:
        mujoco_gl: Backend to request. Defaults to ``wgl`` on Windows and to
            whatever ``MUJOCO_GL`` already holds elsewhere.
        init_cuda: Create a CUDA context first so the discrete GPU serves the
            OpenGL context. See :func:`prefer_discrete_gpu`.

    Returns:
        The value ``MUJOCO_GL`` was left at.
    """
    if init_cuda:
        prefer_discrete_gpu()

    if "robosuite" in sys.modules:
        raise RuntimeError(
            "configure_rendering() must be called before robosuite is imported"
        )

    # Applies on every platform.
    _write_private_macros()

    if sys.platform != "win32":
        return os.environ.get("MUJOCO_GL", "")

    _copy_mujoco_dll()
    _stub_egl_probe()

    backend = mujoco_gl or os.environ.get("MUJOCO_GL") or WINDOWS_MUJOCO_GL
    os.environ["MUJOCO_GL"] = backend
    return backend
