"""Convert a regenerated robomimic dataset to LeRobot format and validate it.

    python scripts/convert_to_lerobot.py --source data/lift/ph/image_256px_2ep.hdf5
    python scripts/convert_to_lerobot.py

Writes a dataset card to `docs/phase-3/dataset_card.md` recording every setting
used, because the instruction string and the state construction have to match what
evaluation does and there is no way to recover them from the files alone.
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.data.to_lerobot import DEFAULT_INSTRUCTION, convert  # noqa: E402
from src.envs.obs_adapter import DEFAULT_CAMERA_MAP  # noqa: E402

logger = logging.getLogger("convert")


def validate(root: Path, repo_id: str, source_frames: int, source_episodes: int,
             instruction: str) -> dict:
    """Load the dataset back and check it against the source."""
    from lerobot.datasets.lerobot_dataset import LeRobotDataset

    dataset = LeRobotDataset(repo_id=repo_id, root=root)
    report = {
        "n_episodes": dataset.num_episodes,
        "n_frames": dataset.num_frames,
        "fps": dataset.fps,
        "episodes_match": dataset.num_episodes == source_episodes,
        "frames_match": dataset.num_frames == source_frames,
        "features": {k: list(v["shape"]) for k, v in dataset.features.items()
                     if "shape" in v},
    }

    sample = dataset[0]
    report["sample_keys"] = sorted(str(k) for k in sample)
    report["task"] = sample.get("task")
    report["task_matches"] = sample.get("task") == instruction

    for key in DEFAULT_CAMERA_MAP.values():
        if key in sample:
            img = sample[key]
            report[key] = {
                "shape": list(img.shape),
                "dtype": str(img.dtype),
                "min": float(img.min()),
                "max": float(img.max()),
            }

    state = np.asarray(sample["observation.state"])
    action = np.asarray(sample["action"])
    report["state"] = {"shape": list(state.shape),
                       "min": float(state.min()), "max": float(state.max())}
    report["action"] = {"shape": list(action.shape),
                        "min": float(action.min()), "max": float(action.max())}

    # Action statistics across the whole dataset. Phase 2 measured the rollout's
    # action distribution; a large discrepancy here would point back at the action
    # adapter rather than at the data.
    all_actions = np.stack([np.asarray(dataset[i]["action"])
                            for i in range(0, dataset.num_frames,
                                           max(1, dataset.num_frames // 500))])
    report["action_stats"] = {
        "sampled": int(all_actions.shape[0]),
        "mean": all_actions.mean(axis=0).tolist(),
        "std": all_actions.std(axis=0).tolist(),
        "min": all_actions.min(axis=0).tolist(),
        "max": all_actions.max(axis=0).tolist(),
    }
    return report


def write_card(path: Path, meta: dict, report: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    names = ["dx", "dy", "dz", "drx", "dry", "drz", "gripper"]
    stats = report["action_stats"]

    lines = [
        "# Phase 3 Dataset Card",
        "",
        "Generated by `scripts/convert_to_lerobot.py`. Every value here is a setting",
        "that evaluation has to agree with, and none of it can be recovered from the",
        "dataset files alone.",
        "",
        "## Provenance",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Source HDF5 | `{meta['source']}` |",
        f"| Task | {meta['task']} / {meta['dataset_type']} |",
        f"| Episodes | {report['n_episodes']} |",
        f"| Frames | {report['n_frames']} |",
        f"| FPS | {report['fps']} |",
        f"| Robot | Panda, 7-DoF |",
        f"| Controller | OSC_POSE, control_delta=True, input range [-1, 1] |",
        "",
        "## Contract",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Instruction (exact string) | `\"{meta['instruction']}\"` |",
        f"| Cameras | {', '.join(f'`{k}` -> `{v}`' for k, v in meta['camera_map'].items())} |",
        f"| Resolution | {meta['resolution']}x{meta['resolution']} |",
        f"| Image storage | PNG (`use_videos=False`) |",
        f"| State | {report['state']['shape'][0]} values, built by `ObsAdapter.build_state` |",
        f"| State normalised | {meta['normalize_state']} |",
        f"| Action | {report['action']['shape'][0]} values |",
        "",
        "The instruction string must be passed verbatim at evaluation time. The state",
        "is constructed by the same function the evaluator uses, so the two cannot",
        "drift apart.",
        "",
        "## Image orientation",
        "",
        "Frames are stored **upright**. robosuite renders bottom-left-origin and",
        "robomimic flips every RGB observation on the way out",
        "(`env_robosuite.py:190`), so data arriving from robomimic is already the",
        "right way up and is not flipped again. The rollout path has no such flip,",
        "which is what `obs_adapter.upright()` is for.",
        "",
        "## Action statistics",
        "",
        f"Sampled over {stats['sampled']} frames.",
        "",
        "| dim | mean | std | min | max |",
        "| --- | --- | --- | --- | --- |",
    ]
    for i, name in enumerate(names[:len(stats["mean"])]):
        lines.append(
            f"| {name} | {stats['mean'][i]:+.4f} | {stats['std'][i]:.4f} | "
            f"{stats['min'][i]:+.4f} | {stats['max'][i]:+.4f} |"
        )

    lines += [
        "",
        "## Validation",
        "",
        "| Check | Result |",
        "| --- | --- |",
        f"| Episode count matches source | {report['episodes_match']} |",
        f"| Frame count matches source | {report['frames_match']} |",
        f"| Instruction round-trips | {report['task_matches']} |",
    ]
    for key in DEFAULT_CAMERA_MAP.values():
        if key in report:
            info = report[key]
            lines.append(
                f"| `{key}` | {info['shape']} {info['dtype']}, "
                f"range [{info['min']:.3f}, {info['max']:.3f}] |"
            )
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path,
                        default=REPO_ROOT / "data" / "lift" / "ph" / "image_256px.hdf5")
    parser.add_argument("--repo-id", default="local/lift_ph")
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--instruction", default=DEFAULT_INSTRUCTION)
    parser.add_argument("--fps", type=int, default=20)
    parser.add_argument("--n-episodes", type=int, default=None)
    parser.add_argument("--raw-state", action="store_true",
                        help="store unscaled degrees; must match the evaluator")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--card", type=Path,
                        default=REPO_ROOT / "docs" / "phase-3" / "dataset_card.md")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    if not args.source.is_file():
        print(f"not found: {args.source}\nrun scripts/regenerate_obs.py first")
        return 1

    root = args.root or REPO_ROOT / "data" / "lerobot" / args.repo_id.replace("/", "_")
    if root.exists():
        if not args.overwrite:
            print(f"{root} already exists; pass --overwrite")
            return 1
        shutil.rmtree(root)

    import h5py

    with h5py.File(args.source, "r") as f:
        episodes = sorted(f["data"].keys(), key=lambda s: int(s.split("_")[1]))
        if args.n_episodes:
            episodes = episodes[:args.n_episodes]
        source_episodes = len(episodes)
        source_frames = int(sum(f[f"data/{e}"].attrs["num_samples"] for e in episodes))
        resolution = int(f[f"data/{episodes[0]}/obs/agentview_image"].shape[1])

    print(f"source      : {args.source}")
    print(f"destination : {root}")
    print(f"episodes    : {source_episodes}, frames: {source_frames}")
    print(f"instruction : {args.instruction!r}\n")

    convert(
        source=args.source,
        repo_id=args.repo_id,
        root=root,
        instruction=args.instruction,
        fps=args.fps,
        n_episodes=args.n_episodes,
        normalize_state=not args.raw_state,
    )

    report = validate(root, args.repo_id, source_frames, source_episodes,
                      args.instruction)

    size = sum(p.stat().st_size for p in root.rglob("*") if p.is_file())
    print(f"\n{'=' * 70}\nVALIDATION\n{'=' * 70}")
    print(f"episodes    : {report['n_episodes']} (source {source_episodes}) "
          f"{'OK' if report['episodes_match'] else 'MISMATCH'}")
    print(f"frames      : {report['n_frames']} (source {source_frames}) "
          f"{'OK' if report['frames_match'] else 'MISMATCH'}")
    print(f"instruction : {report['task']!r} "
          f"{'OK' if report['task_matches'] else 'MISMATCH'}")
    print(f"state       : {report['state']['shape']} "
          f"range [{report['state']['min']:.3f}, {report['state']['max']:.3f}]")
    print(f"action      : {report['action']['shape']} "
          f"range [{report['action']['min']:.3f}, {report['action']['max']:.3f}]")
    for key in DEFAULT_CAMERA_MAP.values():
        if key in report:
            info = report[key]
            print(f"{key:<34}: {info['shape']} {info['dtype']} "
                  f"[{info['min']:.3f}, {info['max']:.3f}]")
    print(f"on disk     : {size / 2**20:.1f} MiB")

    meta = {
        "source": str(args.source),
        "task": "lift",
        "dataset_type": "ph",
        "instruction": args.instruction,
        "camera_map": DEFAULT_CAMERA_MAP,
        "resolution": resolution,
        "normalize_state": not args.raw_state,
    }
    write_card(args.card, meta, report)
    (root / "conversion_report.json").write_text(
        json.dumps({"meta": meta, "report": report}, indent=2), encoding="utf-8"
    )
    print(f"\ndataset card: {args.card}")

    ok = (report["episodes_match"] and report["frames_match"]
          and report["task_matches"])
    print(f"\n{'OK' if ok else 'VALIDATION FAILED'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
